import { Photo } from "@/types/photo";

export const PHOTOS: Photo[] = [
  {
    id: "1",
    imageUrl: "https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=1200&q=85",
    caption: "Fifth Avenue",
    location: "New York City",
    year: "c. 1908",
    photographer: "Unknown",
    story: `At the beginning of the twentieth century, Fifth Avenue was already the spine of New York's ambition. Horse-drawn carriages competed for cobblestone with the city's first motorised automobiles, and the clatter of iron wheels on stone was the city's constant music.\n\nThe mansions of the Vanderbilts and Astors still lined the avenue's upper reaches, their limestone façades whitened by soot and ambition alike. Fashionable ladies descended from broughams in rustling silk, while newsboys hawked the morning edition for a penny.\n\nThe avenue had a particular quality at dusk — the gaslit shop windows threw gold across the pavement, and the horse traffic thinned so that a pedestrian might finally hear their own footsteps. Photographers of the era returned to this corner again and again, drawn by the collision of old money and arriving modernity.\n\nBy 1910, the last Vanderbilt mansion would begin its slow retreat before the department stores. The photograph you see here captures a world in its final season of confidence, before the great disruptions of the coming decades altered everything beyond recognition.`,
  },
  {
    id: "2",
    imageUrl: "https://images.unsplash.com/photo-1543039625-14cbd3802e7d?w=1200&q=85",
    caption: "The Steel Mill Workers",
    location: "Pittsburgh, Pennsylvania",
    year: "c. 1912",
    photographer: "Lewis Hine",
    story: `Lewis Hine came to Pittsburgh's mills with a plate camera and a sense of moral urgency. The men in this photograph have just ended a twelve-hour shift; their faces carry the particular blankness of profound exhaustion, a look Hine documented throughout the industrial heartland.\n\nThe steel mills of this era ran without pause, consuming men in day and night rotations. A "turn" lasted twelve hours, and a man might work seven days before a single Sunday off. The heat at the furnace mouth could reach eight hundred degrees Fahrenheit. Workers wore no protective equipment beyond leather aprons.\n\nHine's photographs were published in survey reports and newspapers, slowly building the public pressure that would eventually lead to labour reform. He believed the camera was not a neutral instrument — it could be aimed at injustice and made to speak against it.\n\nMany of the men in his Pittsburgh series were immigrants from Eastern Europe, recruited by agents who met ships at Ellis Island. They spoke little English. Their wages were sent home in careful amounts, building a new country out of sweat and discipline. Their names were rarely recorded.`,
  },
  {
    id: "3",
    imageUrl: "https://images.unsplash.com/photo-1533929736458-ca588d08c8be?w=1200&q=85",
    caption: "The Grand Arcade",
    location: "Milan, Italy",
    year: "c. 1895",
    photographer: "Fratelli Alinari",
    story: `The Galleria Vittorio Emanuele II had been open for barely thirty years when Fratelli Alinari made this exposure, and already it had become the drawing room of Milan. The iron and glass vault overhead was an engineering marvel that the city regarded with proprietary pride.\n\nMilanese gentlemen would cross the Galleria's octagonal center and pause to rotate their heel on the mosaic bull of Turin — a ritual said to bring good luck, though the origin of the superstition was already half-forgotten by the time the photograph was made.\n\nThe bookshops and cafés that lined the arcade in 1895 catered to a leisured class with time to read and argue over espresso. Journalists from the Corriere della Sera walked here. Verdi was said to have taken his afternoon coffee at the Savini, watching the tourists with the tolerant amusement of a man who belonged to the place by right.\n\nThe Galleria survived two world wars largely intact, though bombs damaged its glass roof in 1943. What one sees today is almost exactly what the Alinari brothers photographed — the same marble floor, the same ironwork, the same quality of light at midday.`,
  },
  {
    id: "4",
    imageUrl: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&q=85",
    caption: "Alpine Morning",
    location: "Swiss Alps",
    year: "c. 1900",
    photographer: "Unknown",
    story: `Before the age of reliable mountain photography, the Alps existed in the European imagination largely through painting — Turner's apocalyptic visions and the romantic landscapes of Caspar David Friedrich. The camera changed that relationship profoundly.\n\nThis photograph was almost certainly made by a professional expedition photographer, since the equipment required — heavy glass plates, chemical baths, a portable darkroom — demanded the resources of a commercial enterprise. The exposure likely took several seconds, which is why no human figures appear among the rocks.\n\nThe fin-de-siècle was the golden age of alpinism. Gentlemen from London and Vienna arrived each summer with alpine guides and the ambition to tick summits from a list. The guides themselves — men from Zermatt and Chamonix who had grown up reading the mountains — are the uncelebrated heroes of this era. Their names rarely appear in the expedition accounts their clients published.\n\nThe village below the ridge would have been in shadow when this plate was exposed, its farmers already at work in the high meadows with the cattle that would be brought down before the first autumn snow.`,
  },
  {
    id: "5",
    imageUrl: "https://images.unsplash.com/photo-1444464666168-49d633b86797?w=1200&q=85",
    caption: "Portrait in the Photographer's Studio",
    location: "Vienna, Austria",
    year: "c. 1885",
    photographer: "Unknown",
    story: `By the 1880s, the carte-de-visite portrait had become a social institution across Europe. Every respectable family maintained an album, and a sitting at the photographer's studio was a significant occasion — occasion enough to wear one's finest clothes and compose one's expression with considerable care.\n\nThe studio shown here is typical of the era: a painted backdrop of indeterminate landscape, a side chair or column to lean upon, and the studio's north-facing windows providing the diffuse light that photographers of the period required. Exposures still ran to several seconds, and the subjects were advised not to smile — it was difficult to hold the expression for so long without it becoming a grimace.\n\nVienna in this decade was at the height of its imperial confidence. The Ringstrasse was newly completed. Brahms was composing in an apartment off the Karlsplatz. The young Sigmund Freud was completing his medical studies. The city's population had doubled in twenty years, fed by migration from every corner of the Empire.\n\nWhoever sat for this portrait carried that world with them, its particular weight and certainty. They could not have known that within thirty years the empire would be gone, dissolved by war and revolution into a dozen successor states.`,
  },
  {
    id: "6",
    imageUrl: "https://images.unsplash.com/photo-1549488344-cbb6c34f3bd5?w=1200&q=85",
    caption: "The Harbour at Dawn",
    location: "Istanbul, Turkey",
    year: "c. 1890",
    photographer: "Abdullah Brothers",
    story: `The Abdullah Brothers — Kevork, Viçen, and Hovsep — were the official photographers to the Ottoman court and among the most accomplished documentarians of their era. They photographed sultans, ambassadors, and ancient monuments with equal precision, building an archive that now constitutes one of the most important visual records of the late Ottoman world.\n\nThe Golden Horn in this photograph is still a working waterway — caiques loaded with produce from the Asian shore, ferries threading between the docks, the minarets of Sultanahmet rising on the far bank above the morning haze.\n\nConstantinople in 1890 was a city of perhaps one million souls speaking dozens of languages. Greeks, Armenians, Jews, and Muslims lived in distinct but overlapping quarters, each with their own churches, schools, and newspapers. The city's commerce was transacted in a hybrid language that blended Turkish, Greek, Italian, and French, understood by all and belonging to none.\n\nThe wooden yalıs that lined the Bosphorus in this era were largely gone by 1930, replaced by stone apartment buildings. The photograph records a city that no longer exists, not only in its physical form but in its entire social composition.`,
  },
  {
    id: "7",
    imageUrl: "https://images.unsplash.com/photo-1499856871958-5b9627545d1a?w=1200&q=85",
    caption: "Rue de Rivoli",
    location: "Paris, France",
    year: "c. 1900",
    photographer: "Eugène Atget",
    story: `Eugène Atget spent thirty years photographing Paris with the methodical devotion of an archivist and the eye of an artist. He rose before dawn, loaded his view camera onto a handcart, and walked the streets before the city fully woke, capturing what he called "documents for artists" — images of shop fronts, archways, spiral staircases, and the reflections of trees in rain-wet cobblestones.\n\nAtget worked alone and sold his prints cheaply to painters and designers who needed visual reference. He was nearly seventy when the Surrealists discovered him and declared his photographs unconsciously dreamlike. Man Ray published them in La Révolution Surréaliste without asking permission. Atget was bemused. He had been trying to describe things as they were.\n\nThe Rue de Rivoli runs the length of the Tuileries, its arcades sheltering bookshops and tea rooms that Atget documented in dozens of images. The light he preferred was early and soft, before the sun moved above the roofline and created the harsh shadows he disliked.\n\nAtget died in 1927 with most of his archive uncatalogued. His assistant and neighbour, Berenice Abbott, bought the collection and spent the next decades ensuring its survival. Without her intervention, his work would have been dispersed and likely lost.`,
  },
  {
    id: "8",
    imageUrl: "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=1200&q=85",
    caption: "The Thames at Night",
    location: "London, England",
    year: "c. 1905",
    photographer: "Unknown",
    story: `The Thames in this period was still a working river in the fullest sense — its surface busy with lighters, barges, and steam tugs from before first light until well into the night. The docks that lined its lower reaches were the engine of an empire: sugar from Barbados, tea from Assam, wool from Australia, all passing through St. Katherine's and the India Docks before moving inland by rail.\n\nThe light on the water comes from the gas lamps of the Embankment, installed in the 1860s when Bazalgette rebuilt the river's north bank. The lamps represented a political as much as an engineering triumph — the city's attempt to reclaim its waterfront from the miasma it had spent a century creating.\n\nA night photograph required either a long exposure or the newer fast orthochromatic plates that were becoming available in the early 1900s. The reflections of light on water made for technically simpler night work than the streets, and several photographers of the period specialised in what they called "nocturnes" — a word borrowed deliberately from Whistler, who had made the Thames at night his own subject twenty years earlier.\n\nThe bridges in the background — likely Waterloo or Blackfriars — were lit by lamps at their piers, creating the chains of light that gave these nocturne photographs their particular elegance.`,
  },
  {
    id: "9",
    imageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&q=85",
    caption: "Market Day",
    location: "Marrakech, Morocco",
    year: "c. 1920",
    photographer: "Unknown",
    story: `The Jemaa el-Fna had been the beating heart of Marrakech for nearly a thousand years when this photograph was made. The square's name translates roughly as "assembly of the dead" — a reference, some scholars believe, to the public executions that once took place here, or perhaps to the heads of criminals displayed at the gates of the adjacent palace.\n\nBy the 1920s, the square was dominated by its day market: water sellers in red costumes, snake charmers, storytellers whose circles of listeners grew and shrank with the drama of the narrative, medicine men with their assemblages of dried herbs and animal parts, scribes who composed letters for the illiterate.\n\nFrench rule had come to Morocco in 1912, and by the time this photograph was made, European visitors arrived in numbers. Many came specifically to photograph the square, which had acquired a reputation as the most photographically obliging place in North Africa — all that colour, all that activity, all those faces. Whether the square's inhabitants experienced this attention as interest or intrusion was a question few European visitors paused to consider.\n\nThe sounds of the square at dusk — the Gnawa musicians beginning their evening performances, the call to prayer from the Koutoubia's minaret, the sellers crying their last prices — these things the photograph cannot capture.`,
  },
  {
    id: "10",
    imageUrl: "https://images.unsplash.com/photo-1580428180098-24b353d7e9d9?w=1200&q=85",
    caption: "The Fishermen's Return",
    location: "Brittany, France",
    year: "c. 1910",
    photographer: "Unknown",
    story: `The fishing communities of Brittany had barely changed in outward form since the seventeenth century when photographers first began documenting them in the 1860s. The women still wore the elaborate white coiffes that identified their particular village; the men still went out in the same types of flat-bottomed boats that their great-grandfathers had used.\n\nBut this surface continuity concealed profound changes. The sardine canneries that had opened along the Breton coast in the 1880s had transformed the economy of fishing from subsistence to industry. Women who had previously processed fish at home now worked in factory conditions for wages, and the rhythms of their labour were set not by the tides but by the cannery whistle.\n\nThis photograph shows the boats coming in on the afternoon tide, the catch already gutted and packed in ice, the men moving with the particular efficient exhaustion of people accustomed to physical labour. Their faces carry an expression common to fishing photographs of the era — a wariness, perhaps, of the camera and its social implications, or simply the blank aftermath of concentration.\n\nThe coasts these men fished would be altered by the end of the century through overfishing, industrial trawling, and the slow warming of the Atlantic. The sardines that had made the region prosperous grew scarce, then rare, and the canneries one by one closed.`,
  },
  {
    id: "11",
    imageUrl: "https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=1200&q=85",
    caption: "Varanasi Ghats",
    location: "Varanasi, India",
    year: "c. 1915",
    photographer: "Unknown",
    story: `Varanasi is among the oldest continuously inhabited cities on earth, and the ghats — the stepped stone embankments that descend to the Ganges — have been photographed since the earliest days of photography in India. Yet the ghats resist easy documentation. They are too layered, too dense with simultaneous activity, for any single image to contain.\n\nThis photograph was likely made in the early morning, when the light was manageable and the pilgrims who came to bathe in the river were at their most numerous. Hindus believe the Ganges at Varanasi to be especially sacred — that to bathe here washes away a lifetime's accumulated sin, and that to die here is to achieve direct liberation from the cycle of rebirth.\n\nThe city during the British Raj occupied an unusual position. It was simultaneously a major commercial centre, a seat of Sanskrit learning, and one of the most important pilgrimage sites in the subcontinent. The British administration recognised its symbolic importance and largely left its religious life undisturbed, while the new railway line brought pilgrims from distances that would previously have taken months to travel.\n\nThe view from the river at dawn, with the temples and towers rising behind the ghats, was among the most photographed scenes in the world by 1900. It appeared in every illustrated travelogue of India, serving — as all such images serve — both as documentation and as projection of what the photographer's audience wished to see.`,
  },
  {
    id: "12",
    imageUrl: "https://images.unsplash.com/photo-1569429593410-b498b3fb3387?w=1200&q=85",
    caption: "The Ice Harvest",
    location: "New England, USA",
    year: "c. 1898",
    photographer: "Unknown",
    story: `Before mechanical refrigeration, ice was a commodity as essential as coal, harvested from frozen ponds and rivers each winter and stored in insulated warehouses for distribution throughout the year. The ice trade was one of New England's significant industries, and the men who cut and hauled ice were specialists with their own tools, techniques, and culture.\n\nThe cutting began when the ice reached a depth of at least fourteen inches, considered the minimum for safe working and for efficient insulation in storage. Teams of horses pulled ice plows that scored a grid across the surface; men with handsaws then cut blocks free and floated them to the shore, where they were hoisted by derrick onto horse-drawn sleds for transport to the icehouse.\n\nFrederic Tudor, the "Ice King," had pioneered the commercial ice trade in the early nineteenth century, shipping New England ice to the Caribbean and eventually to India. By the time this photograph was made, the trade was enormous but also threatened: the mechanical ice-making machines first demonstrated in the 1870s were becoming commercially viable, and the natural ice harvesters could feel the ground shifting under them.\n\nBy 1920, most of the great natural icehouses of New England had closed. The ponds where men had worked through January and February winters reverted to recreation and wildlife, taking their particular winter industry with them into history.`,
  },
];
